import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    name: "Havit HV-G69 USB Gamepad",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 1,
    category: "Gaming",
    imageUrl: "/images/products/product-1-bg-1.png",
  },
  {
    name: "iPhone 14 Plus , 6/128GB",
    reviews: 5,
    price: 899.0,
    discountedPrice: 99.0,
    _id: 2,
    category: "Mobiles",
    imageUrl: "/images/products/product-2-bg-1.png",
  },
  {
    name: "Apple iMac M1 24-inch 2021",
    reviews: 5,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 3,
    category: "Computers",
    imageUrl: "/images/products/product-3-bg-1.png",
  },
  {
    name: "MacBook Air M1 chip, 8/256GB",
    reviews: 6,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 4,
    category: "Laptops",
    imageUrl: "/images/products/product-4-bg-1.png",
  },
  {
    name: "Apple Watch Ultra",
    reviews: 3,
    price: 99.0,
    discountedPrice: 29.0,
    _id: 5,
    category: "Wearables",
    imageUrl: "/images/products/product-5-bg-1.png",
  },
  {
    name: "Logitech MX Master 3 Mouse",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 6,
    category: "Accessories",
    imageUrl: "/images/products/product-6-bg-1.png",
  },
  {
    name: "Apple iPad Air 5th Gen - 64GB",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 7,
    category: "Tablets",
    imageUrl: "/images/products/product-7-bg-1.png",
  },
  {
    name: "Asus RT Dual Band Router",
    reviews: 15,
    price: 59.0,
    discountedPrice: 29.0,
    _id: 8,
    category: "Networking",
    imageUrl: "/images/products/product-8-bg-1.png",
  },
];

export default shopData;
